apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: goerli-geth
  name: goerli-geth-data
  namespace: validators
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
