version: "3"
services:
  geth:
    image: ethereum/client-go:v1.10.15
    ports:
      - 30303:30303
      - 8545:8545
    entrypoint: [ "geth", "--http", "--http.addr", "0.0.0.0" ]
    volumes:
      - geth_data:/root/.ethereum
    healthcheck:
      test: "wget --no-cache -S --header 'Content-Type: application/json'
        --post-data='{\"jsonrpc\":2.0,\"method\":\"web3_clientVersion\",\"params\
        \":[],\"id\":1}' 0.0.0.0:8545 -O-"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  geth_data:
