version: "3.7"
services:
  geth:
    image: ethereum/client-go:v1.10.15
    ports:
      - 30303:30303
      - "${GETH_RPC_PORT:-8545}:8545"
    # GETH_NETWORK is one of mainnet (default) | goerli | rinkeby | ropsten
    entrypoint:
      [
        "geth",
        "--${GETH_NETWORK:-mainnet}",
        "--http",
        "--http.addr",
        "0.0.0.0",
        "--http.port",
        "${GETH_RPC_PORT:-8545}"
      ]
    deploy:
      placement:
        constraints:
          - node.labels.chaindata == true
    volumes:
      - geth_data:/root/.ethereum
    healthcheck:
      test: "wget --no-cache -S --header 'Content-Type: application/json'
        --post-data='{\"jsonrpc\":2.0,\"method\":\"web3_clientVersion\",\"params\
        \":[],\"id\":1}' 0.0.0.0:8545 -O-"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  geth_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/nfs/docker/volumes/geth_${GETH_NETWORK:-mainnet}_data'
