version: "3.7"
services:
  geth:
    image: ethereum/client-go:v1.10.15
    ports:
      - "${GETH_NETWORK_PORT:-30303}:30303"
    entrypoint: >
      geth --${GETH_NETWORK:-mainnet} --port ${GETH_NETWORK_PORT:-30303}
           --http --http.addr 0.0.0.0 --http.port ${GETH_HTTP_RPC_PORT:-8545}
           --ws --ws.addr 0.0.0.0 --ws.port ${GETH_WS_RPC_PORT:-8546}
           --metrics --metrics.expensive --metrics.influxdbv2
           --metrics.influxdb.endpoint http://influxdb:8086
           --metrics.influxdb.database geth-${GETH_NETWORK:-mainnet}
           --metrics.influxdb.bucket ${DOCKER_INFLUXDB_INIT_BUCKET}
           --metrics.influxdb.organization ${DOCKER_INFLUXDB_INIT_ORG}
           --metrics.influxdb.token ${INFLUX_TOKEN}
    deploy:
      placement:
        constraints:
          - node.labels.chaindata == true
    volumes:
      - geth_data:/root/.ethereum
    networks:
      default:
        aliases:
          - geth-${GETH_NETWORK:-mainnet}
    healthcheck:
      test: >
        wget --no-cache -S -O-
        --header "Content-Type: application/json"
        --post-data='{"jsonrpc":2.0,"method":"web3_clientVersion","params":[],"id":1}'
        0.0.0.0:${GETH_HTTP_RPC_PORT:-8545}
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  influxdb:
    image: influxdb:2.1
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET
    deploy:
      placement:
        constraints:
          - node.labels.metrics == true
    networks:
      default:
        aliases:
          - influxdb

  nimbus_beacon_node:
    image: statusim/nimbus-eth2:amd64-latest
    restart: unless-stopped
    stop_grace_period: 1m
    deploy:
      placement:
        constraints:
          - node.labels.chaindata == true
    ports:
      - 127.0.0.1:9190:9190/tcp
      - 127.0.0.1:8008:8008/tcp
      - 9000:9000/tcp
      - 9000:9000/udp
    volumes:
      - nibmus_data:/home/user/nimbus-eth2/build/data
    command: >-
      --network=prater
      --data-dir=/home/user/nimbus-eth2/build/data/shared_prater_0
      --web3-url=ws://geth-${GETH_NETWORK:-mainnet}:${GETH_WS_RPC_PORT:-8546}
      --nat=extip:${NIMBUS_EXTERNAL_IP} --log-level=DEBUG --tcp-port=9000
      --udp-port=9000 --rpc --rpc-address=0.0.0.0 --rpc-port=9190 --metrics
      --metrics-address=0.0.0.0 --metrics-port=8008

volumes:
  nibmus_data:
  geth_data:
  influxdb_data:

networks:
  traefik-swarm:
    external: true
