version: "3.7"
services:
  geth:
    image: ethereum/client-go:v1.10.15
    ports:
      - "${GETH_NETWORK_PORT:-30303}:30303"
      - "${GETH_HTTP_RPC_PORT:-8545}:8545"
      - "${GETH_WS_RPC_PORT:-8546}:8546"
    # GETH_NETWORK is one of mainnet (default) | goerli | rinkeby | ropsten
    entrypoint:
      [
        "geth",
        "--${GETH_NETWORK:-mainnet}",
        "--port",
        "${GETH_NETWORK_PORT:-30303}",
        "--http",
        "--http.addr",
        "0.0.0.0",
        "--http.port",
        "${GETH_HTTP_RPC_PORT:-8545}",
        "--ws",
        "--ws.addr",
        "0.0.0.0",
        "--ws.port",
        "${GETH_WS_RPC_PORT:-8546}"
      ]
    deploy:
      placement:
        constraints:
          - node.labels.chaindata == true
    volumes:
      - geth_data:/root/.ethereum
    networks:
      - traefik-swarm
    labels:
      - traefik.enable="true"
      - traefik.http.routers.eth-${GETH_NETWORK:-mainnet}.rule="Host(`eth.rpc.${GETH_NETWORK:-mainnet}.lan`)"
      - traefik.http.routers.eth-${GETH_NETWORK:-mainnet}.entryPoints="web"
      - traefik.http.routers.eth-${GETH_NETWORK:-mainnet}.service="eth-${GETH_NETWORK:-mainnet}"
      - traefik.http.services.eth-${GETH_NETWORK:-mainnet}.loadbalancer.server.port="8123"
    healthcheck:
      test: "wget --no-cache -S --header 'Content-Type: application/json'
        --post-data='{\"jsonrpc\":2.0,\"method\":\"web3_clientVersion\",\"params\
        \":[],\"id\":1}' 0.0.0.0:${GETH_HTTP_RPC_PORT:-8545} -O-"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  geth_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/nfs/docker/volumes/geth_${GETH_NETWORK:-mainnet}_data'

networks:
  traefik-swarm:
    external: true