apiVersion: apps/v1
kind: Deployment
metadata:
  name: goerli-nethermind
  namespace: validators
spec:
  selector:
    matchLabels:
      app: goerli-nethermind
  revisionHistoryLimit: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: goerli-nethermind
    spec:
      containers:
        - name: goerli-nethermind
          resources:
            requests:
              memory: 4Gi
              cpu: 3000m
            limits:
              memory: 8Gi
              cpu: 16000m
          args: [
            "--JsonRpc.Enabled=true",
            "--datadir=data",
            "--config=goerli",
            "--Metrics.Enabled=true",
            "--Network.DiscoveryPort=30305",
            "--Network.P2PPort=30305",
            "--Init.WebSocketsEnabled=true",
            "--JsonRpc.Host=0.0.0.0",
            "--JsonRpc.WebSocketsPort=8546"
          ]
          image: nethermind/nethermind:1.12.4
          ports:
            - containerPort: 30305
            - containerPort: 9091
            - containerPort: 8546
          volumeMounts:
            - mountPath: /nethermind/data
              name: goerli-nethermind-data
      restartPolicy: Always
      volumes:
        - name: goerli-nethermind-data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 50Gi
