apiVersion: v1
kind: Service
metadata:
  name: goerli-nethermind
  namespace: validators
spec:
  selector:
    app: goerli-nethermind
  ports:
    - name: "ws-rpc"
      port: 8546
      targetPort: 8546
    - name: "metrics"
      port: 9091
      targetPort: 9091
status:
  loadBalancer: {}
