apiVersion: v1
kind: Service
metadata:
  name: goerli-openethereum
  namespace: validators
spec:
  selector:
    app: goerli-openethereum
  ports:
    - name: "ws-rpc"
      port: 8546
      targetPort: 8546
    - name: "metrics"
      port: 3000
      targetPort: 3000
status:
  loadBalancer: {}
