apiVersion: apps/v1
kind: Deployment
metadata:
  name: goerli-erigon
  namespace: validators
spec:
  selector:
    matchLabels:
      app: goerli-erigon
  revisionHistoryLimit: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: goerli-erigon
    spec:
      initContainers:
        - name: chown
          image: busybox
          command:
            - chown
            - -R
            - "1000:1000"
            - /home/erigon/goerli
          volumeMounts:
            - mountPath: /home/erigon/goerli
              name: goerli-erigon-data
      containers:
        - name: goerli-erigon
          resources:
            requests:
              memory: 4Gi
              cpu: 3000m
            limits:
              memory: 8Gi
              cpu: 16000m
          args: [
            "erigon",
            "--datadir=/home/erigon/goerli",
            "--chain=goerli"
          ]
          image: thorax/erigon:v2022.01.01
          ports:
            - containerPort: 30303
            - containerPort: 6060
            - containerPort: 8546
          volumeMounts:
            - mountPath: /home/erigon/goerli
              name: goerli-erigon-data
      restartPolicy: Always
      volumes:
        - name: goerli-erigon-data
          ephemeral:
            volumeClaimTemplate:
              spec:
                # dataSource:
                #   name: goerli-erigon-data-snapshot-latest
                #   kind: VolumeSnapshot
                #   apiGroup: snapshot.storage.k8s.io
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 50Gi
