version: "3.7"
services:
  nimbus_beacon_node:
    image: statusim/nimbus-eth2:amd64-latest
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - geth
    deploy:
      placement:
        constraints:
          - node.labels.chaindata == true
    ports:
      - 127.0.0.1:9190:9190/tcp
      - 127.0.0.1:8008:8008/tcp
      - 9000:9000/tcp
      - 9000:9000/udp
    volumes:
      - nibmus_data:/home/user/nimbus-eth2/build/data
    command: >-
      --network=prater
      --data-dir=/home/user/nimbus-eth2/build/data/shared_prater_0
      --web3-url=ws://geth-${GETH_NETWORK:-mainnet}:${GETH_WS_RPC_PORT:-8546}
      --nat=extip:${NIMBUS_EXTERNAL_IP} --log-level=${NIMBUS_LOG_LEVEL:-INFO} --tcp-port=9000
      --udp-port=9000 --rpc --rpc-address=0.0.0.0 --rpc-port=9190 --metrics
      --metrics-address=0.0.0.0 --metrics-port=8008

volumes:
  nibmus_data:
    name: nimbus-prater-data

networks:
  traefik-swarm:
    external: true
  geth:
    external: true
    name: geth-${GETH_NETWORK:-mainnet}
