apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prater-nimbusku
  name: prater-nimbus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
