apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prater-nimbusku
  name: prater-nimbus-data
  namespace: validators
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
