version: "3.7"
services:
  grafana:
    image: grafana/grafana:8.3.3
    restart: always
    networks:
      - traefik-swarm
      - default
    deploy:
      placement:
        constraints:
          - node.labels.metrics == true
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: "Host(`grafana.lan`)"
      traefik.http.routers.grafana.entryPoints: "web"
      traefik.http.routers.grafana.service: "grafana"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
    deploy:
      mode: global
      labels:
        prometheus-job: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'

  prometheus:
    image: prom/prometheus
    user: root
    networks:
      geth:
      traefik-swarm:
      default:
        aliases:
          - prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    deploy:
      placement:
        constraints:
          - node.labels.metrics == true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.rule: "Host(`prometheus.lan`)"
      traefik.http.routers.prometheus.entryPoints: "web"
      traefik.http.routers.prometheus.service: "prometheus"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.43.0
    networks:
      - traefik-swarm
      - default
    ports:
      - 8081:8080
    deploy:
      mode: global
      labels:
        prometheus-job: cadvisor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.cadvisor.rule: "Host(`cadvisor.lan`)"
      traefik.http.routers.cadvisor.entryPoints: "web"
      traefik.http.routers.cadvisor.service: "cadvisor"
      traefik.http.services.cadvisor.loadbalancer.server.port: "8080"
    command: -docker_only

volumes:
  grafana_data:
  influxdb_data:
    name: influxdb-data
  influxdb_config:
    name: influxdb-config

configs:
  prometheus.yml:
    external: true

networks:
  host:
    external: true
    name: host
  geth:
    external: true
    name: geth-goerli
  traefik-swarm:
    external: true