---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-pv-claim
spec:
  # Leaving this commented on purpose in source code so that it errors out.
  # storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench
spec:
  template:
    spec:
      containers:
        - name: dbench
          image: fbuchmeier/dbench:latest
          imagePullPolicy: Always
          env:
            - name: DBENCH_MOUNTPOINT
              value: /dbench-data
              # - name: DBENCH_QUICK
              #   value: "yes"
              # - name: FIO_SIZE
              #   value: 1G
              # - name: FIO_OFFSET_INCREMENT
              #   value: 256M
              # - name: FIO_DIRECT
              #   value: "0"
          volumeMounts:
            - name: dbench-pv
              mountPath: /dbench-data
      restartPolicy: Never
      volumes:
        - name: dbench-pv
          persistentVolumeClaim:
            claimName: dbench-pv-claim
  backoffLimit: 4
